"""initial schema

Revision ID: 4e72f55a3778
Revises: 
Create Date: 2026-04-17 20:05:38.888657+00:00
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e72f55a3778'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('league', sa.String(length=120), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('formation', sa.String(length=16), nullable=True),
    sa.Column('playing_style', sa.String(length=64), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('api_football_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_api_football_id'), ['api_football_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_teams_league'), ['league'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_name'), ['name'], unique=False)

    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('free_user', 'pro_analyst', 'club_scout', 'admin', name='user_role'), nullable=False),
    sa.Column('subscription_tier', sa.Enum('free', 'pro', 'scout', 'enterprise', name='subscription_tier'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('matches',
    sa.Column('home_team_id', sa.Uuid(), nullable=False),
    sa.Column('away_team_id', sa.Uuid(), nullable=False),
    sa.Column('league', sa.String(length=120), nullable=False),
    sa.Column('season', sa.String(length=16), nullable=False),
    sa.Column('match_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'live', 'finished', 'postponed', 'cancelled', name='match_status'), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('venue', sa.String(length=180), nullable=True),
    sa.Column('referee', sa.String(length=180), nullable=True),
    sa.Column('api_football_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matches_api_football_id'), ['api_football_id'], unique=True)
        batch_op.create_index('ix_matches_away_team', ['away_team_id'], unique=False)
        batch_op.create_index('ix_matches_date_status', ['match_date', 'status'], unique=False)
        batch_op.create_index('ix_matches_home_team', ['home_team_id'], unique=False)
        batch_op.create_index('ix_matches_league_season', ['league', 'season'], unique=False)

    op.create_table('players',
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('nationality', sa.String(length=80), nullable=True),
    sa.Column('position', sa.String(length=32), nullable=True),
    sa.Column('preferred_foot', sa.Enum('left', 'right', 'both', name='preferred_foot'), nullable=True),
    sa.Column('jersey_number', sa.Integer(), nullable=True),
    sa.Column('market_value_eur', sa.Integer(), nullable=True),
    sa.Column('current_team_id', sa.Uuid(), nullable=True),
    sa.Column('api_football_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['current_team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_players_api_football_id'), ['api_football_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_players_current_team_id'), ['current_team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_position'), ['position'], unique=False)

    op.create_table('ai_predictions',
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('home_win_prob', sa.Float(), nullable=False),
    sa.Column('draw_prob', sa.Float(), nullable=False),
    sa.Column('away_win_prob', sa.Float(), nullable=False),
    sa.Column('predicted_home_score', sa.Integer(), nullable=True),
    sa.Column('predicted_away_score', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('key_factors', sa.JSON(), nullable=True),
    sa.Column('actual_result', sa.Enum('home_win', 'draw', 'away_win', name='predicted_outcome'), nullable=True),
    sa.Column('was_correct', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'model_version', name='uq_ai_predictions_match_model')
    )
    with op.batch_alter_table('ai_predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_predictions_match_id'), ['match_id'], unique=False)
        batch_op.create_index('ix_ai_predictions_model_version', ['model_version'], unique=False)

    op.create_table('match_events',
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('goal', 'own_goal', 'penalty_awarded', 'penalty_missed', 'yellow_card', 'red_card', 'substitution', 'var', 'kickoff', 'halftime', 'fulltime', name='event_type'), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=True),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('extra_info', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_events', schema=None) as batch_op:
        batch_op.create_index('ix_match_events_match_minute', ['match_id', 'minute'], unique=False)

    op.create_table('player_stats',
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('match_id', sa.Uuid(), nullable=True),
    sa.Column('season', sa.String(length=16), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('minutes_played', sa.Integer(), nullable=False),
    sa.Column('pass_accuracy', sa.Float(), nullable=True),
    sa.Column('shots_on_target', sa.Integer(), nullable=False),
    sa.Column('dribbles_completed', sa.Integer(), nullable=False),
    sa.Column('tackles_won', sa.Integer(), nullable=False),
    sa.Column('xg', sa.Float(), nullable=True),
    sa.Column('xa', sa.Float(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('player_stats', schema=None) as batch_op:
        batch_op.create_index('ix_player_stats_match_id', ['match_id'], unique=False)
        batch_op.create_index('ix_player_stats_player_season', ['player_id', 'season'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_stats', schema=None) as batch_op:
        batch_op.drop_index('ix_player_stats_player_season')
        batch_op.drop_index('ix_player_stats_match_id')

    op.drop_table('player_stats')
    with op.batch_alter_table('match_events', schema=None) as batch_op:
        batch_op.drop_index('ix_match_events_match_minute')

    op.drop_table('match_events')
    with op.batch_alter_table('ai_predictions', schema=None) as batch_op:
        batch_op.drop_index('ix_ai_predictions_model_version')
        batch_op.drop_index(batch_op.f('ix_ai_predictions_match_id'))

    op.drop_table('ai_predictions')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_position'))
        batch_op.drop_index(batch_op.f('ix_players_name'))
        batch_op.drop_index(batch_op.f('ix_players_current_team_id'))
        batch_op.drop_index(batch_op.f('ix_players_api_football_id'))

    op.drop_table('players')
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index('ix_matches_league_season')
        batch_op.drop_index('ix_matches_home_team')
        batch_op.drop_index('ix_matches_date_status')
        batch_op.drop_index('ix_matches_away_team')
        batch_op.drop_index(batch_op.f('ix_matches_api_football_id'))

    op.drop_table('matches')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_name'))
        batch_op.drop_index(batch_op.f('ix_teams_league'))
        batch_op.drop_index(batch_op.f('ix_teams_api_football_id'))

    op.drop_table('teams')
    # ### end Alembic commands ###
